---
title: "p8105_hw1_st3431"
output: html_document
date: "2022-09-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Problem 1

```{r description}
data("penguins", package = "palmerpenguins")

summary(penguins)
  summary(penguins$flipper_length_mm)
  summary(penguins$species)

nrow(penguins)

ncol(penguins)

mean(penguins$flipper_length_mm, na.rm=T)

```

```{r scatterplot}
plot_df=
  tibble(
    x=penguins$bill_length_mm,
    y=penguins$flipper_length_mm
  )
  
ggplot(plot_df, aes(color=penguins$species, x = x, y = y)) + geom_point()
```

## Problem 2

```{r}
hw_df=tibble(random_sample=rnorm(10), 
  vec_logic=random_sample>0, 
  vec_character=c("a","b","c","d","e","f","g","h","i","j"), 
  vec_factor=factor(c("low", "medium", "high", "low","medium","high", "low","medium","high","low")) )

#means of variable within the df
  mean(hw_df$vec_logic)
  mean(hw_df$vec_character)
  mean(hw_df$vec_factor)
  mean(hw_df$random_sample)
```

```


